language: python
python: 
  - "2.7"
  - "3.6" 
  - "3.8" 
  - "pypy"
  - "pypy3" 
  - "nightly"
virtualenv:
  system_site_packages: true
install:
  - pip install lazy_object_proxy
  - python setup.py -q install  
script: pytest
  
